apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment-dev
spec:
  template:
    metadata:
      name: pod-javadb-dev
      labels:
        app: pod-javadb-dev
    spec:
      containers:
        - name: container-pod-javadb
          image: bocunha/grupoone-springweb
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits: 
              memory: "800Mi" 
              cpu: "1"
  replicas: 2
  selector:
    matchLabels:
      app: pod-javadb-dev